### ISSUE TITLE
Finding the largest inscribed rectangle for an irregularly shaped projected display

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#1]
Finding the largest inscribed rectangle for an irregularly shaped projected display, as accomplished in the first step of the proposed layout algorithm, has been a standard procedure for a decade now (cf., Raskar et al.'s iLamps in SIGGRAPH 2003). A similar approach was presented by Cotting and Gross (Interactive environment-aware display bubbles, UIST 2006). The problem with these techniques is that the entire content is uniformly scaled down or deformed, even though display space could be compressed by just removing gaps between originally sized items. Unfortunately, as the layout technique in this paper scales down the entire content as a first step, it suffers from the same limitation. In Figure 5, for instance, the individual arrows could preserve almost original size, while being positioned to avoid display outline cropping and overlap with neighboring arrows.

**Comment by jamcnaughton** [comment]
I feel this may be more relevant to an older version where I was more explicit about the finding the largest inscribed rectangle - now I just refer to it generically (but we can throw in the suggested references if they're not in there already).

I think we'll have to list the initial scaling as an unavoidable cost of the approach - but discuss possible ways of negating it such as:
a) Scaling the layout but not the content to fit the largest inscribed rectangle if overlapping and occlusion of the display sides is not an issue.
b) scaling items back up when the position pulling stage is carried out (scaling relative to size of the pulling vector with a cap at the original size - or possibly no cap if scaling not too relevant to the content).

**Comment by jamcnaughton** [comment]
Fixed already - there is a discussion on methods and shortcomings of finding the maximal rectangle on page 6.

Discussion of possible methods of avoiding the initial scaling could be included in a future paper on guidelines.
