### ISSUE TITLE
Dedicated "Implementation" section?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#11]
The implementation details are outlined in the Discussion and Conclusion sections. The authors should consider introducing a dedicated implementation section.

**Comment by jamcnaughton** [comment]
This makes sense, I'd left it out previously as then the lack of an actual study becomes more obvious. But an implementation section could include details on the basic study I carried out too.

**Comment by jamcnaughton** [comment]
From an old version - we do have an implementation section, though I think it will now be better as a Study section.
