### ISSUE TITLE
Lengthy Discussion section

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#12]
Some parts of the paper are pretty lengthy, especially in the Discussion section.

**Comment by jamcnaughton** [comment]
Creation of an implementation, and perhaps study, section could break up some of the content from this section.

Creation of a subsection discussing guidelines could also help break this section down.

We'll really need to cut back on some parts anyway to fit in the new content.

**Comment by jamcnaughton** [comment]
The Discussion (soon to be  'Observations') section isn't actually that long - this must have referred to when it was combine with Implementation (soon to be 'Study').
