### ISSUE TITLE
Virtual projection stage algorithm

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#13]
Half of the first paragraph of Section 4.1 elaborates that the virtual projection stage preserves the items' topology and avoids cropping at the display boundary. On the other hand, it is not clearly described which algorithm is used or has been adapted to calculate the similarity transform of the input rectangle.

**Comment by jamcnaughton** [comment]
I'l have to explicitly state that the algorithm used is a basic one which runs as so: 
1) Get the change in translation, scale and rotation between the original display rectangle and the largest inscribed rectangle.
2) Apply the same transformations with the same values to the visual contents in the appropriate sequence. 

I could dig into my code to get it for psuedo-code but I think its really basic.

**Comment by jamcnaughton** [comment]
Add psuedo-code of process discussed above to section 4.1.

**Comment by jamcnaughton** [comment]
Algorithm and detailed explanation added.
