### ISSUE TITLE
Real world table example

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#14]
It would have been interesting to see how the resulting layout looks like on a photo of a real, irregularly shaped tabletop display.

**Comment by jamcnaughton** [comment]
I have the photos from my study - plus a photo of prototype circular tabletop we worked on.

**Comment by jamcnaughton** [comment]
![research 13](https://cloud.githubusercontent.com/assets/1144661/25456277/521881b8-2aca-11e7-921c-ebf2938c0467.jpg)
![tablesetup](https://cloud.githubusercontent.com/assets/1144661/25456278/52194ca6-2aca-11e7-90a1-d794d885a240.png)

**Comment by jamcnaughton** [comment]
Photos of study and prototype should resolve this issue.

**Comment by jamcnaughton** [comment]
Added photos.
