### ISSUE TITLE
Recommendations for finding trade-offs between interfering display issues for different applications

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#15]
A set of recommendations for finding trade-offs between interfering display issues for different applications, supported by example images, could have been useful.

**Comment by jamcnaughton** [comment]
A guidelines section would be a really good output. I don't think it'd take too long to add.  

I think the guide lines could simply be a number of questions and related steps of the algorithm:
- What types of visual contents are in my app? [e.g. Background, controls, manipulable objects. Apply the algorithm separately to each different type]
- Should all of this visual content be on screen and bares no relations to other visual contents? [If not then don't transform to fit the largest inscribed rectangle.]
- Should all of this visual content maintain its layout? [If so then don't apply the pull position algorithm.]

**Comment by jamcnaughton** [comment]
If this paper is accepted we could write up a follow up presenting some guidelines and perform a survey by providing them to developers and asking for their opinions and considerations for adopting them. Out of scope for this paper.
