### ISSUE TITLE
"Important that software becomes display shape independent" argument?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#16]
On page 9, you make the argument: "_...For this reason it is important that software becomes display shape independent._" I am not convinced of that argument. In fact, it goes against current trends. When Apple switched from the iPhone 3s to the iPhone 4, they doubled the pixel density while keeping the aspects the same. This allowed for backwards compatibility. When they switched from the 4s to the 5, they increased the length of the phone to move it from the 3:2 format to the 16:9 format. Programs running in 3:2 format still work; they just don't utilize some of the display. It seems much more probable that new display technologies will be built with the past in mind (perhaps unduly constrained by them), rather than imposing new challenges on systems ill-equipped to deal with them. In general, developers utilize the specifics of a platform, not wasting their time on theoretical future directions.

**Comment by jamcnaughton** [comment]
Discussion of chicken/egg nature of the problem. As software does not support non-rectangular displays then non-rectangular displays are not built (however, they are - but rarely - suggesting a desire in some places). We could make a point that the implementation of the algorithm at a low level in a framework could enable any supported software to potentially adapt to different display shapes, with little to no work needed by developers.

I have a number of arguments for the need to support non-rectangular displays from my masters relating to places where non-typical displays have been used in the past, often to fit better into certain locations - a desire often driven by the growth of ubiquitous computing.

Also I have notes from an interview with a furniture designer who wanted to have a non-rectangular display in his designs which could run usual software - proving a real-world need for this sort of adaptability.

I'll dig these up and add them.

**Comment by jamcnaughton** [comment]
Above argument to be added to the appropriate place in the Conclusion + highlighting little progress in this area in recent years.

**Comment by jamcnaughton** [comment]
There's already quite a big argument for it throughout the paper - I've tied it all together in the conclusion a bit more.
