### ISSUE TITLE
More sophisticated techniques?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#2]
As the proposed layout component is obviously able to access all content items individually, more sophisticated techniques from document or window layout research (e.g., grid-based or constraint-based layout techniques) could have been adopted instead.  A hierarchical management of content items, such as most GUI toolkits provide, could have helped to group items that should maintain their spatial relations (as, for instance, the example in Figure 6). I am missing a discussion about alternative layout algorithms and why they have been found unsuitable for irregularly shaped tabletop displays.

**Comment by jamcnaughton** [comment]
I think I may have made amendments in regard to this feedback in subsequent versions of the article. There is some discussion on how the main benefit of the proposed approach is that it gives developers a lot of options, one of which is the ability to maintain the relative layout of visual content which is useful if the layout is relevant, the other techniques detailed do not allow for this. This approach can also be applied automatically (with parameters regarding which steps of the algorithm are applied to which types of content) which could be desirable in some circumstances whereas many of the comparable techniques out there require significant manual input.

Perhaps we could explicitly state the above somewhere.

**Comment by jamcnaughton** [comment]
Fixed already, there is a discussion of GUI building tools like SUPPLE in the conclusion.
