### ISSUE TITLE
Expand the scope

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#21]
_I think the fact that the authors focus on tabletop systems is really limiting the scope of this paper and I have no doubt that whatever they are doing is applicable to a large variety of systems (e.g. smart watch, mobile devices, wearable computer etc.). They say it in the conclusion but I would suggest removing the focus on tabletops from the introduction and title and rather be more generalist straight from the beginning._

**Comment by jamcnaughton** [comment]
Expanding focus will be part of further research as discussed in the conclusion.
