### ISSUE TITLE
Motivation behind the automatic algorithm

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#22]
_An automatic process to adapt visual content is a great idea but how does it fits with the references 31 and 32 that demonstrated that different shapes need different layout? In particular the authors of these two papers have shown that there are some guidelines that could be used to automatize such a process (e.g. using symmetry). Currently references 31 and 32 are cited at the end of this paper when they should be almost first because they are the closest related work. These studies presented visual composition guidelines of text and website for non-rectangular displays. Contrary to what is stated in this paper they do no focus on legacy systems but attempt to generalize design principles to any type of non-rectangular 2D displays. It thus feels like the authors missed something important here and the guideline from these papers should have may be served as rationale for the algorithm proposed in this work._

**Comment by jamcnaughton** [comment]
Move discussion of these two papers to the background section and note how they present guidelines which place more responsibility on software and content-designers. Then summarise in discussion section how this technique requires minimal input from developers allowing them to design freely.
