### ISSUE TITLE
Motivation of DSDI section

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#23]
_- Are those categories exhaustive? where do they came from? there is currently a lack of rationale and the categories seem to me really linked to the algorithm proposed after rather than being generalist. E.g. why is it that cropping is at the top on Figure 1? I guess one other possibility could have been to deform the UIs (like a fish eye lens).
- each DSDI could do with an illustration for each case.
- Figure 1 should be explained first because it was unclear for me that cropping was on a different layer than the other. Explaining Figure 1 straight at the beginning of this section will make the text more appealing and clear._

**Comment by jamcnaughton** [comment]
In DSDI section: Clearly state that the DSDIs presented are novel and that they were derived from first-hand observations on earlier attempts by the authors to manually fit content to different display shapes. Also discuss the difference between the primary and secondary DSDIs (refer to dsdiFlow). Additionally, note the DSDIs were numbered by the order they were noted by the authors and bare no significance beyond identification.

**Comment by jamcnaughton** [comment]
Resolved in commit 21bb566.
