### ISSUE TITLE
Algorithm section

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#24]
- A brief section of the overall idea could be made in the beginning of this section (may be put Figures 2 and 3 at the beginning as they are great to explain what is happening).
- The virtual projection subsection is ok but 1 page long and to be honest I don’t think it does need that much, in the end this is just a scale/rotate/move of a content. What would be more interesting is to talk about how this technique scale up with very complex shapes, e.g. what if the screens have holes? what is the screen is very long (like a stretch rectangle) etc… and the impact of this phase on the content.
- The position pulling phase is very more interesting but again it is unclear how this technique works with more complex topology of screen, e.g. a jigsaw or something even more strange.
- I don’t think algorithm 1 is necessary
- Overall, I would suggest to first present the step 1 and 2 and then add another section where you discuss how this two steps minimized the DSDI by presenting them one by one with examples. I would also like a section discussing how the algorithm scale up to different/more complex shapes.

**Comment by jamcnaughton** [comment]
- Intro to the algorithm section does summaries the steps of the algorithm. Pictures are better where they are as they should be close to the algorithms that refer to them.
- **I can take out a lot of the virtual projection stuff no problem (I added a lot of it in the last redraft as another reviewer wanted more information on it).**
- **Add discussion of need to investigate more extreme shapes in the conclusion as part of future work.**
- **Remove virtual position algorithm makes sense (again, late addition to appease another reviewer).**
- We already discuss the implications of each stage in the Observations section.

**Comment by jamcnaughton** [comment]
Resolved in commit 9cbd980.
