### ISSUE TITLE
Do a user study?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#26]
Conduct a user study to investigate whether or not the automatic algorithm performs better / differently than the guidelines already proposed in 31/32 … in particular I would suggest doing a proper controlled experiment using a readability task or a search task.
 
Whether or not the results are statistically significant the study would be interesting: if not you can still propose some new iterations on the algorithm to adapt the guidelines.

Also: 

The study protocol and design need to be better detailed. Authors should clarify who used these applications (i.e. number of participants), a precise description of the task, length of the sessions, etc.. Also authors should clearly indicate how they measured the usability of the interface: for instance, when authors say “… were able to be utilised as normal […] without any observable issues”, how do authors know this ? Did they ask participants ? Did participants fill a SUS questionnaire ?
 
In its current form,  the study seems more like a preliminary test than a formal experiment.

**Comment by tomcrick** [comment]
(probably not for this paper, but worth thinking about going forward)

**Comment by jamcnaughton** [comment]
Agreed. Re-structuring paper to be more of a positional paper with a clear statement of an intent to carry out a study in future work as part of the conclusion.

**Comment by jamcnaughton** [comment]
Resolved in commit 887d90a.
