### ISSUE TITLE
Linking algorithm to literature

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#27]
_Propose the same automatic algorithm but discuss in more details how it adapts to more complex shapes as well as how it creates visuals that fit the guidelines from 31 and 32_

**Comment by jamcnaughton** [comment]
Link technique stages to the guidelines they help content adhere to.

**Comment by jamcnaughton** [comment]
On re-reading the guideline papers I found that the advice given isn't really relevant enough to keep calling back to.
