### ISSUE TITLE
Cropping DSDI

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#29]
_It is also not clear to me why the Cropping DSDI is an initial issue, and the others are secondary issues. Cropping is similar to overlapping, in both cases some content is covered. Cropping could simply be resolved by scrolling the content, and then it is much less of an issue than overlapping. It seems more than, as the solution proposed by authors first deals with Cropping, then this issue became Initial. I think authors should clarify this, as it seems that the classification of the DSDIs is driven by the proposed solution, and not the opposite._

**Comment by jamcnaughton** [comment]
Discussion of the DSDI categories needs to be included (primary - can happen when displaying content without modification on a different display shape, secondary - can happen when attempting to resolve initial DSDIs).

**Comment by jamcnaughton** [comment]
Resolved in commit 21bb566.
