### ISSUE TITLE
Complex legacy applications

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#3]
For a better judgment of the strengths and limitations of the proposed technique, it would have been interesting to see how more complex legacy applications, like a rectangular painting application, a text editor, or an e-mail client, would look like on an irregularly shaped tabletop display, with the GUI widgets arranged according to the proposed layout algorithm.

**Comment by jamcnaughton** [comment]
I think it would take too long to add this algorithm into some typical legacy software if we're aiming to submit in the next few weeks - I could produce a mock-up for demonstrative purposes however.

**Comment by jamcnaughton** [comment]
I think legacy applications are out of the scope of this paper.

We could use them as examples and subjects in a future paper on guidelines resulting from this work,
