### ISSUE TITLE
Issues with proposed solution

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#30]
_Concerning the proposed solution, it seems that it is based on a simple couple of operations (projection then pulling) which may be good at fitting the content, but not at proposing the best final layout. I wonder whether the first stage (virtual projection) is a good approach. In particular, rotating the content could bring the aforementioned legibility problems. The second stage solves mainly the Display Use issue, which in my opinion is less important than the Layout DSDI.
 
In other terms, authors propose a solution which is capable of creating a non-rectangular layout, but that does not really optimise it in terms of legibility, usability, etc._

**Comment by jamcnaughton** [comment]
Need to clearly state this is a solution, likely not always the maximal solution but one which can be easily automated and allow developers some control over its execution.

**Comment by jamcnaughton** [comment]
Resolved in commit e6f2247
