### ISSUE TITLE
Check new paragraph ordering in "Conclusions and Future Work"

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#48]
Moved around the first few paragraph in Section 5 to start stronger -- see what you think!

**Comment by jamcnaughton** [comment]
Look good to me, I spotted 2 little things for me to change then I'll close this issue.
1) 'Scaling -- when a content item is resized whilst maintaining its aspect ratio -- a visual element may be performed to avoid the cropping of content.' => 'Scaling -- when a content item is resized whilst maintaining its aspect ratio -- **on** a visual element may be performed to avoid the cropping of content.'
2) 'The technique**s** presented' => 'The technique presented'
