### ISSUE TITLE
Attractive force in position pulling stage

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#6]
In the position pulling stage, the attractive force of the display boundary is defined by the distance of content item to the visible display outline, and the distance between the rectangular content boundary and the visible boundary. Is the item's shape incorporated in this calculation? Are there repulsive forces between items to avoid overlaps?

**Comment by jamcnaughton** [comment]
I think we'll have to explicitly state: 
a) The items shape is not incorporated in the calculation, it just runs off its centroid.
b) There are no repulsive forces in the approach presented but they could be added as an additional step in the algorithm for if developers want to minimise overlap.

**Comment by jamcnaughton** [comment]
I need to add a line explaining that the pulling force works off shapes' centroids.

The idea of repulsive forces to avoid overlapping can be included in a future paper on guidelines.

**Comment by jamcnaughton** [comment]
Added a line to resolve this.
