### ISSUE TITLE
Manual re-modelling

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#7]
The display outline needs to be re-modeled manually. How is this accomplished? Is it possible to draw the outline directly on the output display?

**Comment by jamcnaughton** [comment]
I think this feedback relates to how do we inform the algorithm of the display shape. 

We should explicitly state that how the algorithm is informed of the shape is down to the implementation - one possible method (as I've used) is to create a vector file that relates to a specific display shape which is loaded up beforehand as part of the software's configuration.

**Comment by jamcnaughton** [comment]
Partly fixed already. Just need to add a line or two about the loading of vector graphic files to load display shape geometry into the Study (formally implementation) section.

**Comment by jamcnaughton** [comment]
Added discussion of the vector files.
