### ISSUE TITLE
Technique activation clarification

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#8]
It is mentioned that the technique is activated at the initial content mapping, and if the "application needs to transform an item to a specific position" without user intervention. An example of an occasion where the system would need to transform an item without user input would support understanding. Also, it would be interesting to know whether these layout changes take the previous item positions into account to maintain spatial stability.

**Comment by jamcnaughton** [comment]
So one example we could use is the addition of new content. When a new item is set to be added in the display's 'centre', the algorithm would be applied to ensure it was added in the centre of the maximum inscribed rectangle. I could probably flesh this example out a bit more to cover this feedback. 

We could then discuss animations, like an item moving into a new layout (useful for tidying layout but ensuring users can track where items have moved to via the animation). These would have to take into account the item's current location and apply the algorithm to the locations used in its transformations.

**Comment by jamcnaughton** [comment]
Partly already fixed in the paper.

Need to add a better example of applying the algorithm to items directly positioned by the software - the animation example above should do.

**Comment by jamcnaughton** [comment]
Added better example of when the technique would be applied.
