### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#9]
The term "display shape dependence issue" sounds strange to me. Terms like "criteria" or "requirements" seem more appropriate than "issues" (mind that this reviewer is not an English native speaker).

**Comment by jamcnaughton** [comment]
If we can think of something catchier than DSDI then I'm all for it.

- Change in Display Shape Issue: CIDS Issue?
- Display Shape Related Issue: DSR Issue?

**Comment by jamcnaughton** [comment]
I'm fine with DSDI as they are issues that occur due to software's dependence on a specific display shape.
